# Generated by Django 5.2.5 on 2026-03-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productclick_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='matched_product_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
