# Generated by Django 5.2.5 on 2026-03-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_searchhistory_matched_product_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='coins',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cost_coins',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='game',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]