# Generated by Django 5.2.5 on 2026-03-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_purchase_inventory_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('unit_design_image', models.ImageField(blank=True, null=True, upload_to='unit_designs/')),
                ('unit_design_emoji', models.CharField(blank=True, max_length=16, null=True)),
                ('unit_design_color', models.CharField(default='#28a745', max_length=20)),
                ('unit_design_border_color', models.CharField(default='#1e7e34', max_length=20)),
                ('in_stock', models.BooleanField(default=True)),
                ('category', models.CharField(default='Game Top-Up', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]